############################
#Build project for production
#
#
############################
version: 0.2



phases:
  ###########################################
  #Uses a python runtime
  #Note that you do not need the \ to escape
  #aws cli commands
  ###########################################
  install:
    runtime-versions:
       python: 3.7
    commands:
      - echo Entered the install phase...

      - BUILD_ENVIRONMENT=prod
      - pip install -r tests/requirements.txt
      - ls -l
    finally:

  #Builds the cloudformation stack that contains the
  #static webpage
  build:
    commands:
      - echo $BUILD_ENVIRONMENT
      - echo Entered the build phase...
      - echo Build started on `date`


      - aws sts get-caller-identity
      - aws sts assume-role --role-arn arn:aws:iam::972323850308:role/prodPersonalWebsiteCrossAccountRo-CrossAccountRole-1CTVWLAH998J4
        --role-session-name prod-build

      - python builds/py/prod_stack_build.py
      #merges dev branch into master now that all tests have
      #been passed and artifacts created
      - aws codecommit merge-branches-by-fast-forward
        --source-commit-specifier dev
        --destination-commit-specifier master
        --repository-name devdocs

  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

artifacts:
  files:
    - ./logs/*
