############################
#Build project for production
#
#
############################
version: 0.2



phases:
  ###########################################
  #Uses a python runtime
  #Note that you do not need the \ to escape
  #aws cli commands
  ###########################################
  install:
    runtime-versions:
       python: 3.7
    commands:
      - echo Entered the install phase...

      - BUILD_ENVIRONMENT=prod
      - pip install -r tests/requirements.txt
      - ls -l
    finally:

  #Builds the cloudformation stack that contains the
  #static webpage
  build:
    commands:
      - echo $BUILD_ENVIRONMENT
      - echo Entered the build phase...
      - echo Build started on `date`

      - aws sts get-caller-identity
      - aws sts assume-role --role-arn arn:aws:iam::972323850308:role/prodPersonalWebsiteCrossAccountRo-CrossAccountRole-1CTVWLAH998J4
        --role-session-name prod-build

        ############################################3
        # According to this documentation:
        #
        # https://docs.aws.amazon.com/codebuild/latest/userguide/sample-pipeline-multi-input-output.html
        #
        # Any CodeBuild project that gets passed multiple
        # input artifacts gets the secondary artifact directory location
        # stored in an environment variable using the following
        # naming convention:
        # $CODEBUILD_SRC_DIR_<yourInputArtifactName>
        #
        # $CODEBUILD_SRC_DIR_BuildDev contains the artifacts
        #  from the Dev stage
        #./apps and ./docs directory after everything was built in
        # the development stage
        ##############################################
      - cd $CODEBUILD_SRC_DIR_BuildDev

      - ls -l
      #python script needs to be run where the
      #built html files are sitting
      - python $CODEBUILD_SRC_DIR/builds/py/prod_stack_build.py

      #moving back to original code repo location
      - cd $CODEBUILD_SRC_DIR

      #These tests need to run in the working directory
      #where the source code is
      - python tests/test_prod_aws_resources.py

      #merges dev branch into master now that all tests have
      #been passed and artifacts created
      - aws codecommit merge-branches-by-fast-forward
        --source-commit-specifier dev
        --destination-commit-specifier master
        --repository-name devdocs

  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

artifacts:
  files:
    - ./logs/*
