# cross account role modified from this aws news update:
# https://aws.amazon.com/blogs/apn/easing-the-creation-of-cross-account-roles-for-customers/
Description:
  Cross account role that lives in production bucket for
  updating a static hosted website

Parameters:
  BucketName:
    Type: String
    Default: ryanrigato.com
    Description:
        The name for the bucket where the static webpage is hosted
  DevelopmentAccount:
    Type: String
    Default: 1234567
    Description: Account id allowed to assume the cross account role

  #root defaults to all users
  DevelopmentUser:
    Type: String
    Default: user_name
    Description:
      Username you want to be able to assume the cross-account role
      in the development account

Resources:
  CrossAccountRole:
    Type: AWS::IAM::Role
    Properties:
      #trust policy for the role = who is allowed to assume the role
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
        #arn of the user allowed to assume the cross account role:
        #"arn:aws:iam::account_id:user_name"
          Principal:
            AWS:
              !Join
              #What we use to concatenate items
              #followed by a list of items to include
              #in the string
                - ''
                - - 'arn:aws:iam::'
                  - !Ref DevelopmentAccount
                  - ':'
                  - !Ref DevelopmentUser

        Version: '2012-10-17'
      #permissions policy for the role =
      #once the role is assumed what resources int the prod
      #account are allowed to be used
      Path: /
      Policies:
          - PolicyName: DevAccountAuthorization
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Sid: S3WebsiteListBuckets
                  Effect: Allow
                  #######################################
                  #Allowing the cross account role to list
                  #all buckets in parent account
                  #######################################
                  Action:
                    - s3:ListBucket
                    - s3:ListAllMyBuckets
                  Resource:
                    - "*"

                  #######################################
                  #Allowing the cross account role to
                  #update a specific bucket provided by the
                  #BucketName parameter
                  #######################################
                - Sid: S3EditWebsiteBucket
                  Effect: Allow

                  Action:
                    # - s3:GetObject
                    # - s3:DeleteObject
                    # - s3:PutObject
                    - s3:ListBucket
                    - s3:ListAllMyBuckets
                  Resource:
                    - "*"
Outputs:
  CrossAccountRoleArn:
    Description: Arn for the cross account role
    Value: !GetAtt CrossAccountRole.Arn
