Description:
  Cross account role that lives in production bucket for >
  updating webpage

Parameters:
  BucketName:
    Type: String
    Default: ryanrigato.com
    Description:
        The name for the bucket where the static webpage is hosted

Resources:
  BackendIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [cloudformation.amazonaws.com]
        Version: '2012-10-17'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      Path: /
      Policies:
          - PolicyName: DevAccountAuthorization
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Sid: S3Allow
                  Effect: Allow
                  #######################################
                  #Allowing lambda to perform a PutItem on
                  #DynamoDB
                  #
                  #######################################
                  Action:
                    #- iam:PassRole
                    - s3:ListBucket
                    - s3:ListAllMyBuckets
                    - s3:GetObject
                    - s3:DeleteObject
                    - s3:PutObject
                  Resource:
                    - "*"
Outputs:
  BackendIamRole:
    Description: Reference to IAM role used for templates/backend.yml
    Value: !Ref BackendIamRole
